# Generated by Django 3.2.4 on 2021-07-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_auto_20210706_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Категория',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Название продукта',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='Описание',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='Цена',
        ),
    ]
