# Generated by Django 3.2.4 on 2021-07-06 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0004_auto_20210706_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорию', 'verbose_name_plural': 'Категории'},
        ),
    ]
