# Generated by Django 3.2.4 on 2021-07-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0005_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Название категории',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название категории'),
        ),
    ]
