# Generated by Django 3.2.4 on 2021-07-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0006_auto_20210706_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Название продукта',
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название продукта'),
        ),
    ]
