# Generated by Django 3.2.4 on 2021-07-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0007_auto_20210706_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Категория',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Описание',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Цена',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegram_bot.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Цена'),
        ),
    ]
