# Generated by Django 3.2.4 on 2021-07-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0008_auto_20210706_1713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False, 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
