# Generated by Django 3.2.4 on 2021-07-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0011_auto_20210710_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
