# Generated by Django 3.2.4 on 2021-07-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0012_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
