# Generated by Django 3.2.4 on 2021-07-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0014_user_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=True, verbose_name='Подписка на уведомления'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ID пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=20, null=True, verbose_name='Юзернейм в телеграме'),
        ),
    ]
