# Generated by Django 3.2.4 on 2021-07-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0015_auto_20210712_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/defaults/bot_404.png/', upload_to='uploads/products/%Y_%m_%d/'),
        ),
    ]
