# Generated by Django 3.2.4 on 2021-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0016_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='uploads/defaults/bot_404.png/', upload_to='uploads/products/%Y_%m_%d/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveBigIntegerField(null=True, verbose_name='Цена'),
        ),
    ]
