# Generated by Django 3.2.4 on 2021-07-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0018_broadcast_order_promo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'Промоакция', 'verbose_name_plural': 'Промокации'},
        ),
        migrations.AddField(
            model_name='promo',
            name='text',
            field=models.TextField(default=None, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
