# Generated by Django 3.2.4 on 2021-07-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0019_auto_20210713_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
    ]
