# Generated by Django 3.2.4 on 2021-07-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0021_alter_promo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads/broadcast/%Y_%m_%d', verbose_name='Фото (по желанию)'),
        ),
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/promo/%Y_%m_%d', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
