# Generated by Django 3.2.4 on 2021-07-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0022_auto_20210713_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
