# Generated by Django 3.2.4 on 2021-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0024_auto_20210713_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/promo/%Y_%m_%d', verbose_name='Фото'),
        ),
    ]
