# Generated by Django 3.2.4 on 2021-07-18 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0027_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Broadcast',
        ),
    ]
