# Generated by Django 3.2.4 on 2021-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0033_alter_promo_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=None, max_length=1024, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promo',
            name='text',
            field=models.TextField(default=None, max_length=1024, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
