# Generated by Django 3.2.4 on 2021-07-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0037_auto_20210729_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_0',
            new_name='image',
        ),
    ]
