# Generated by Django 3.2.4 on 2022-01-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0040_auto_20210729_2153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.AlterModelOptions(
            name='promo',
            options={'verbose_name': 'промоакцию', 'verbose_name_plural': 'Промокации'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
